# Generated by Django 3.0.8 on 2020-09-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='Мир закрыт'),
        ),
    ]
