# Generated by Django 3.0.8 on 2020-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20200921_0853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['world', 'x', 'y']},
        ),
        migrations.AddField(
            model_name='world',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
