# Generated by Django 3.0.8 on 2020-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_auto_20201106_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='height',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='world',
            name='width',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
