# Generated by Django 3.0.8 on 2020-11-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20201107_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='ticks_age',
            field=models.IntegerField(default=0),
        ),
    ]
