# Generated by Django 3.0.8 on 2021-08-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_world_ticks_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='local_resource',
            field=models.CharField(blank=True, choices=[(None, 'No Resource'), ('IRN', 'Iron'), ('GLD', 'Gold'), ('SVR', 'Silver'), ('ALM', 'Aluminium'), ('QRZ', 'Quartz'), ('DMD', 'Diamonds'), ('RBY', 'Rubies'), ('SPH', 'Saphires'), ('ABR', 'Amber'), ('EMR', 'Emerald'), ('AMT', 'Amethists'), ('OBS', 'Obsidian'), ('WYV', 'Wyverns'), ('HRS', 'Horses')], max_length=3),
        ),
        migrations.AlterField(
            model_name='celltag',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='world.Cell'),
        ),
        migrations.AlterField(
            model_name='celltag',
            name='name',
            field=models.CharField(choices=[('NAME', 'Name')], max_length=16),
        ),
        migrations.AlterField(
            model_name='poptag',
            name='name',
            field=models.CharField(choices=[('GROWTH', 'Growth'), ('FACTION', 'Faction'), ('CHARACTER', 'Supported Character')], max_length=16),
        ),
        migrations.AlterField(
            model_name='poptag',
            name='pop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='world.Pop'),
        ),
    ]
