# Generated by Django 3.0.8 on 2021-09-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_auto_20210916_1157'),
        ('world', '0008_cellrenamerequest_faction_factionrenamerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactionMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField()),
                ('can_build', models.BooleanField()),
                ('can_use_army', models.BooleanField()),
                ('can_recruit', models.BooleanField()),
                ('title_name', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factions', to='players.Character')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='world.Faction')),
            ],
        ),
    ]
