# Generated by Django 3.0.8 on 2020-11-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20200723_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='character',
        ),
        migrations.AddField(
            model_name='trait',
            name='character',
            field=models.ManyToManyField(to='players.Character'),
        ),
    ]
