# Generated by Django 3.0.8 on 2020-11-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20201114_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
