# Generated by Django 3.0.8 on 2020-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20201114_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='primary_race',
            field=models.CharField(choices=[('HUM', 'Human'), ('ELF', 'Elf'), ('ORC', 'Orc'), ('DWA', 'Dwarf'), ('GOB', 'Goblin'), ('FEY', 'Fey')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='secondary_race',
            field=models.CharField(choices=[('HUM', 'Human'), ('ELF', 'Elf'), ('ORC', 'Orc'), ('DWA', 'Dwarf'), ('GOB', 'Goblin'), ('FEY', 'Fey')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trait',
            name='verbose_name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
