# Generated by Django 3.0.8 on 2021-04-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bloodline_traits',
            field=models.ManyToManyField(to='players.Trait'),
        ),
        migrations.AddField(
            model_name='trait',
            name='static_img_file',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chartag',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='players.Character'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='character',
            field=models.ManyToManyField(related_name='traits', to='players.Character'),
        ),
    ]
