# Generated by Django 3.0.8 on 2021-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_auto_20210402_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bloodline_traits',
            field=models.ManyToManyField(blank=True, to='players.Trait'),
        ),
        migrations.AlterField(
            model_name='trait',
            name='character',
            field=models.ManyToManyField(blank=True, related_name='traits', to='players.Character'),
        ),
    ]
