# Generated by Django 3.0.8 on 2021-04-03 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_auto_20210402_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=players.models.trait_gfx_path),
        ),
        migrations.CreateModel(
            name='RenameRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Character')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
