# Generated by Django 3.0.8 on 2021-05-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_auto_20210403_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartag',
            name='name',
            field=models.CharField(choices=[('bloodline', 'Bloodline'), ('controlled_by', 'Controlled'), ('location', 'Location'), ('clothes', 'Clothes')], max_length=16),
        ),
    ]
