# Generated by Django 3.0.8 on 2021-08-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_auto_20210504_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartag',
            name='name',
            field=models.CharField(choices=[('bloodline', 'Bloodline'), ('controlled_by', 'Controlled'), ('location', 'Location'), ('clothes', 'Clothes'), ('exp_pol', 'Politics Exp'), ('exp_mil', 'Military Exp'), ('exp_eco', 'Economic Exp'), ('exp_sci', 'Science Exp'), ('friend', 'Friend With'), ('enemy', 'Enemy Of')], max_length=16),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STUDY', 'Учиться'), ('TEACH', 'Обучать'), ('RELOCATE', 'Переехать'), ('FRIEND', 'Завести друга'), ('FACT_CREATE', 'Создать фракцию'), ('RENAME_TILE', 'Переименовать город'), ('POP_SUPPORT', 'Собрать народную поддрежку'), ('ARMY_CREATE', 'Создать армию'), ('ARMY_UPGRADE', 'Усилить армию'), ('BATTLE_DESTR', 'Уничтожить армию'), ('CELL_FORT', 'Построить фортификации'), ('CELL_MANA', 'Повысить доходы маны'), ('CELL_FOOD', 'Повысить сбор пищи'), ('CELL_BUILD', 'Построить поселение')], max_length=16)),
                ('work_required', models.IntegerField()),
                ('work_done', models.IntegerField()),
                ('is_current', models.BooleanField()),
                ('arguments', models.CharField(max_length=300)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='players.Character')),
            ],
        ),
    ]
