# Generated by Django 3.0.8 on 2021-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_auto_20210810_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('STUDY', 'Учиться'), ('TEACH', 'Обучать'), ('RELOCATE', 'Переехать'), ('ADVENTURE', 'Отправиться в приключение'), ('FRIEND', 'Завести друга'), ('FACT_CREATE', 'Создать фракцию'), ('RENAME_TILE', 'Переименовать город'), ('POP_SUPPORT', 'Заполучить народную поддрежку'), ('ARMY_CREATE', 'Создать армию'), ('ARMY_UPGRADE', 'Усилить армию'), ('BATTLE_DESTR', 'Уничтожить армию'), ('CELL_FORT', 'Построить фортификации'), ('CELL_MANA', 'Повысить доходы маны'), ('CELL_FOOD', 'Повысить сбор пищи'), ('CELL_BUILD', 'Построить поселение')], max_length=16),
        ),
    ]
