# Generated by Django 3.0.8 on 2021-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_auto_20210901_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartag',
            name='name',
            field=models.CharField(choices=[('bloodline', 'Bloodline'), ('controlled_by', 'Controlled'), ('location', 'Location'), ('clothes', 'Clothes'), ('death', 'Death'), ('exp_pol', 'Politics Exp'), ('exp_mil', 'Military Exp'), ('exp_eco', 'Economic Exp'), ('exp_sci', 'Science Exp'), ('friend', 'Friend With'), ('enemy', 'Enemy Of'), ('lover', 'Lover'), ('spouse', 'Spouse'), ('child', 'Child Of'), ('pregnancy', 'Pregnancy')], max_length=16),
        ),
    ]
